// src/utils/videoConstants.js

export const LOCAL_VIDEO_DATA = [
    // Wellness Videos
    { id: 1, youtubeId: 'o0Q269hXm1Q', title: '5 Simple Habits for Better Mental Health', theme: 'Wellness' },
    { id: 2, youtubeId: 'a_t5zR5-g6Q', title: 'Mindfulness Meditation for Students', theme: 'Wellness' },
    { id: 3, youtubeId: 'lYgC4h-P-3E', title: 'Quick Stress Relief Techniques', theme: 'Wellness' },
    { id: 4, youtubeId: 'hA_0d-0346E', title: 'The Importance of Sleep for Students', theme: 'Wellness' },
    { id: 5, youtubeId: 'xJ2gQ_f-5L4', title: 'Building Resilience in Tough Times', theme: 'Wellness' },
    { id: 22, youtubeId: 'v-bB8L2KxQc', title: 'Yoga for Stress Relief and Focus', theme: 'Wellness' },
    { id: 23, youtubeId: 'yF7V9pW1g24', title: 'Coping with Exam Anxiety', theme: 'Wellness' },
    { id: 24, youtubeId: 'sKxU8P6F_5w', title: 'Journaling for Emotional Clarity', theme: 'Wellness' },
    { id: 25, youtubeId: 'vQ2H6mD4-7A', title: 'Practicing Gratitude Daily', theme: 'Wellness' },
    { id: 26, youtubeId: '1zN0fG3q_W4', title: 'How to Set Healthy Boundaries', theme: 'Wellness' },
    { id: 27, youtubeId: 'T85Yv65Xk-0', title: 'Breathing Exercises for Calm', theme: 'Wellness' },
    { id: 28, youtubeId: 'Ld9h2-8bFqM', title: 'Finding Your Inner Peace', theme: 'Wellness' },
    { id: 29, youtubeId: 'f0m_Gj9K3fA', title: 'Boosting Self-Confidence for Students', theme: 'Wellness' },

    // Finance Videos
    { id: 6, youtubeId: 's_v7_eR2-e8', title: 'Student Budgeting 101: How to Manage Your Money', theme: 'Finance' },
    { id: 7, youtubeId: '0c_2y1q5yGg', title: 'Understanding Student Loans in South Africa', theme: 'Finance' },
    { id: 8, youtubeId: '2qM624q82bQ', title: 'Investing Basics for Young Adults', theme: 'Finance' },
    { id: 9, youtubeId: 'Gg42hSjI9jI', title: 'Saving Tips for University Students', theme: 'Finance' },
    { id: 10, youtubeId: 'e25C_h6Nf_E', title: 'How to Avoid Common Financial Pitfalls', theme: 'Finance' },
    { id: 30, youtubeId: 'N_Q7f1Y1J_0', title: 'Building Good Credit as a Student', theme: 'Finance' },
    { id: 31, youtubeId: 'H_U8f2X-0tE', title: 'Understanding Your First Payslip', theme: 'Finance' },
    { id: 32, youtubeId: 'W_C3e4Y5o6g', title: 'The Power of Compound Interest', theme: 'Finance' },
    { id: 33, youtubeId: 'V_A9z0b1q2c', title: 'Financial Aid & Bursaries Guide SA', theme: 'Finance' },
    { id: 34, youtubeId: 'P_L1d2F3g4h', title: 'Creating an Emergency Fund', theme: 'Finance' },
    { id: 35, youtubeId: 'Q_R5s6T7u8v', title: 'Online Banking Security Tips', theme: 'Finance' },
    { id: 36, youtubeId: 'X_Y9z0a1b2c', title: 'Side Hustles for Students in SA', theme: 'Finance' },
    { id: 37, youtubeId: 'Z_A3b4c5d6e', title: 'Introduction to Shares & Forex', theme: 'Finance' },

    // Health Videos
    { id: 11, youtubeId: 'M-yXz-zW21Y', title: 'Healthy Eating Habits for Busy Students', theme: 'Health' },
    { id: 12, youtubeId: 'P_jYvG01z34', title: 'Quick Home Workouts for Fitness', theme: 'Health' },
    { id: 13, youtubeId: 'k2n2m6T603c', title: 'Boosting Your Immune System Naturally', theme: 'Health' },
    { id: 14, youtubeId: '1_D3-J82_78', title: 'Understanding Common Student Illnesses', theme: 'Health' },
    { id: 15, youtubeId: 'XzYqK93fQ3k', title: 'The Benefits of Regular Physical Activity', theme: 'Health' },
    { id: 38, youtubeId: 'T_U0v1w2x3y', title: 'Staying Hydrated: Why it Matters', theme: 'Health' },
    { id: 39, youtubeId: 'V_A4b5c6d7e', title: 'Simple Meal Prep Ideas for Students', theme: 'Health' },
    { id: 40, youtubeId: 'W_B8c9d0e1f', title: 'Ergonomics for Study & Work', theme: 'Health' },
    { id: 41, youtubeId: 'X_C2d3e4f5g', title: 'Understanding Your Body & Nutrition', theme: 'Health' },
    { id: 42, youtubeId: 'Y_D6e7f8g9h', title: 'Importance of Regular Check-ups', theme: 'Health' },
    { id: 43, youtubeId: 'Z_E0f1g2h3i', title: 'Managing Digital Eye Strain', theme: 'Health' },
    { id: 44, youtubeId: 'A_F4g5h6i7j', title: 'Basics of First Aid for Students', theme: 'Health' },
    { id: 45, youtubeId: 'B_G8h9i0j1k', title: 'Active Lifestyle on a Budget', theme: 'Health' },

    // Youth Corner Videos (South Africa focused)
    { id: 16, youtubeId: '0X_0R7k_0cQ', title: 'Day in the Life of a Software Engineer in SA', theme: 'Youth Corner' },
    { id: 17, youtubeId: 'R-D_r1B0q0E', title: 'Choosing Your Career Path: South African Context', theme: 'Youth Corner' },
    { id: 18, youtubeId: 'w2n_f-2F0Xg', title: 'Entrepreneurship for Youth in South Africa', theme: 'Youth Corner' },
    { id: 19, youtubeId: 'Z-X_g3F0x0A', title: 'Navigating University Life in SA: Tips & Tricks', theme: 'Youth Corner' },
    { id: 20, youtubeId: 'Q-Y_h5J0x0A', title: 'South African Youth & Mental Health: A Discussion', theme: 'Youth Corner' },
    { id: 21, youtubeId: 'h-W_e6I0x0A', title: 'Financial Literacy for SA Students', theme: 'Youth Corner' },
    { id: 46, youtubeId: 'C_H2i3j4k5l', title: 'SA Student Experiences: What to Expect', theme: 'Youth Corner' },
    { id: 47, youtubeId: 'D_I6j7k8l9m', title: 'Volunteering Opportunities for SA Youth', theme: 'Youth Corner' },
    { id: 48, youtubeId: 'E_J0k1l2m3n', title: 'Developing Soft Skills for the SA Job Market', theme: 'Youth Corner' },
    { id: 49, youtubeId: 'F_K4l5m6n7o', title: 'Higher Education Options Beyond University in SA', theme: 'Youth Corner' },
    { id: 50, youtubeId: 'G_L8m9n0o1p', title: 'Youth Activism and Social Change in SA', theme: 'Youth Corner' },
    { id: 51, youtubeId: 'H_M2n3o4p5q', title: 'Understanding Your Rights as a SA Student', theme: 'Youth Corner' },
    { id: 52, youtubeId: 'I_N6o7p8q9r', title: 'Connecting with Fellow Students in SA', theme: 'Youth Corner' },
    { id: 53, youtubeId: 'J_O0p1q2r3s', title: 'Exploring Cultural Heritage in SA', theme: 'Youth Corner' },
];